import Head from "next/head";
import Navbar from "../component/navbar/Navbar";
import Carousel from "../component/Carousel/carousel";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chetan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>
      <Carousel></Carousel>
    </div>
  );
}
